"""Capture-session file formats.

One directory per capture:

    captures/20260819-143205-vici-line/
    ├── session.json      # metadata, schema below
    ├── frames.jsonl      # raw frames, append-only, never rewritten
    ├── decoded.jsonl     # regenerated by `serialtools decode`; raw frame + "decode" key
    ├── raw/<TAP>.bin     # raw byte stream per tap
    └── tap.log           # human-readable text log

frames.jsonl object (schema_version 1):
    seq       int     monotonic within the capture
    ts        float   epoch seconds
    iso       str     local ISO timestamp (for humans)
    src       str     physical tap label the bytes were measured on
    dir       str     logical direction; == src except on rs485-2w where inferred
    dir_conf  float   present only when < 1.0
    len       int
    hex       str
    ascii     str     dots for unprintables
    gap_ms    float   idle time since previous frame on any tap (absent on first)

Old rs232_tap.py JSONL (ts/iso/dir/len/hex/ascii only) still loads: readers
default seq=-1 and src=dir.

decoded.jsonl adds:
    decode    {proto, ok, summary, role?, fields{}, errors[]}
"""

SCHEMA_VERSION = 1

SESSION_KEYS = {"schema_version", "started", "ended", "wiring", "taps", "gap_ms",
                "notes", "device", "tool"}


def validate_session(obj: dict) -> list[str]:
    """Return a list of problems (empty = fine). Advisory, not enforced."""
    problems = []
    for key in ("schema_version", "started", "wiring", "taps"):
        if key not in obj:
            problems.append(f"missing key: {key}")
    if obj.get("schema_version", SCHEMA_VERSION) > SCHEMA_VERSION:
        problems.append(f"newer schema ({obj['schema_version']}) than this tool ({SCHEMA_VERSION})")
    return problems
